// search 

// 缓存key
export const SEARCH_HISTORY_CACHE = 'SEARCH_HISTORY_CACHE';


// 搜索选择
export const SEARCH_SELECT_CHANGE = 'SEARCH_SELECT_CHANGE';

// 搜索关键字
export const SEARCH_KEY_CHANGE= 'SEARCH_KEY_CHANGE';

// 搜索历史
export const SEARCH_HISTORY_UPDATE = 'SEARCH_HISTORY_UPDATE'

// 搜索历史可视
export const SEARCH_HISTORY_VISABLE_CHANGE = 'SEARCH_HISTORY_VISABLE_CHANGE'


