// search 

export const SEARCH_SELECT_CHANGE = 'SEARCH_SELECT_CHANGE';

export const SEARCH_KEY_CHANGE= 'SEARCH_KEY_CHANGE';
export const SEARCH_KEY_CLEAR= 'SEARCH_KEY_CLEAR';

export const SEARCH_HISTORY_CHANGE = 'SEARCH_HISTORY_CHANGE'
export const SEARCH_HISTORY_CLEAN = 'SEARCH_HISTORY_CLEAN'