export default ({
  style: [
    {
      "Id": 0,
      "Code": "quanbu",
      "OriginalColumn": "StyleId",
      "OriginalId": 1,
      "OriginalName": "全部",
      "GroupId": 1,
      "GroupName": "风格",
    },
    {
      "Id": 1,
      "Code": "jianyue",
      "OriginalColumn": "StyleId",
      "OriginalId": 1,
      "OriginalName": "现代简约",
      "GroupId": 1,
      "GroupName": "风格",
    },
    {
      "Id": 2,
      "Code": "zhongshi",
      "OriginalColumn": "StyleId",
      "OriginalId": 39,
      "OriginalName": "中式",
      "GroupId": 1,
      "GroupName": "风格",
    },
    {
      "Id": 3,
      "Code": "oushi",
      "OriginalColumn": "StyleId",
      "OriginalId": 29,
      "OriginalName": "欧式",
      "GroupId": 1,
      "GroupName": "风格",
    },
    {
      "Id": 4,
      "Code": "tianyuan",
      "OriginalColumn": "StyleId",
      "OriginalId": 38,
      "OriginalName": "田园",
      "GroupId": 1,
      "GroupName": "风格",
    },
    {
      "Id": 5,
      "Code": "xingudian",
      "OriginalColumn": "StyleId",
      "OriginalId": 35,
      "OriginalName": "新古典",
      "GroupId": 1,
      "GroupName": "风格",
    },
    {
      "Id": 6,
      "Code": "dizhonghai",
      "OriginalColumn": "StyleId",
      "OriginalId": 8,
      "OriginalName": "地中海",
      "GroupId": 1,
      "GroupName": "风格",
    },
    {
      "Id": 7,
      "Code": "meishixiangcun",
      "OriginalColumn": "StyleId",
      "OriginalId": 6,
      "OriginalName": "美式乡村",
      "GroupId": 1,
      "GroupName": "风格",
    },
    {
      "Id": 8,
      "Code": "dongnanya",
      "OriginalColumn": "StyleId",
      "OriginalId": 40,
      "OriginalName": "东南亚",
      "GroupId": 1,
      "GroupName": "风格",
    },
    {
      "Id": 9,
      "Code": "houxiandai",
      "OriginalColumn": "StyleId",
      "OriginalId": 4,
      "OriginalName": "后现代",
      "GroupId": 1,
      "GroupName": "风格",
    },
    {
      "Id": 10,
      "Code": "rishi",
      "OriginalColumn": "StyleId",
      "OriginalId": 7,
      "OriginalName": "日式",
      "GroupId": 1,
      "GroupName": "风格",
    },
    {
      "Id": 11,
      "Code": "fugu",
      "OriginalColumn": "StyleId",
      "OriginalId": 36,
      "OriginalName": "复古",
      "GroupId": 1,
      "GroupName": "风格",
    },
    {
      "Id": 12,
      "Code": "hunda",
      "OriginalColumn": "StyleId",
      "OriginalId": 42,
      "OriginalName": "混搭",
      "GroupId": 1,
      "GroupName": "风格",
    },
    {
      "Id": 13,
      "Code": "qita",
      "OriginalColumn": "StyleId",
      "OriginalId": 41,
      "OriginalName": "其他",
      "GroupId": 1,
      "GroupName": "风格",
    }
  ],
  kind: [
    {
      "Id": 0,
      "Code": "quanbu",
      "OriginalColumn": "KindId",
      "OriginalId": 1,
      "OriginalName": "全部",
      "GroupId": 1,
      "GroupName": "空间",
    },
    {
      "Id": 1,
      "Code": "keting",
      "OriginalColumn": "KindId",
      "OriginalId": 1,
      "OriginalName": "客厅",
      "GroupId": 2,
      "GroupName": "空间",
    },
    {
      "Id": 1,
      "Code": "chufang",
      "OriginalColumn": "KindId",
      "OriginalId": 5,
      "OriginalName": "厨房",
      "GroupId": 2,
      "GroupName": "空间",
    },
    {
      "Id": 14,
      "Code": "woshi",
      "OriginalColumn": "KindId",
      "OriginalId": 2,
      "OriginalName": "卧室",
      "GroupId": 2,
      "GroupName": "空间",
    },
    {
      "Id": 16,
      "Code": "yangtai",
      "OriginalColumn": "KindId",
      "OriginalId": 4,
      "OriginalName": "阳台",
      "GroupId": 2,
      "GroupName": "空间",
    },
    {
      "Id": 17,
      "Code": "canting",
      "OriginalColumn": "KindId",
      "OriginalId": 6,
      "OriginalName": "餐厅",
      "GroupId": 2,
      "GroupName": "空间",
    },
    {
      "Id": 18,
      "Code": "shufang",
      "OriginalColumn": "KindId",
      "OriginalId": 7,
      "OriginalName": "书房",
      "GroupId": 2,
      "GroupName": "空间",
    },
    {
      "Id": 19,
      "Code": "qingshaonianfang",
      "OriginalColumn": "KindId",
      "OriginalId": 8,
      "OriginalName": "儿童房",
      "GroupId": 2,
      "GroupName": "空间",
    },
    {
      "Id": 71,
      "Code": "weishengjian",
      "OriginalColumn": "KindId",
      "OriginalId": 3,
      "OriginalName": "卫生间",
      "GroupId": 2,
      "GroupName": "空间",
    },
    {
      "Id": 72,
      "Code": "yimaojian",
      "OriginalColumn": "KindId",
      "OriginalId": 15,
      "OriginalName": "衣帽间",
      "GroupId": 2,
      "GroupName": "空间",
    }
  ],
  part: [
    {
      "Id": 1,
      "Code": "quanbu",
      "OriginalColumn": "PartId",
      "OriginalId": 22,
      "OriginalName": "全部",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 21,
      "Code": "xuanguan",
      "OriginalColumn": "PartId",
      "OriginalId": 22,
      "OriginalName": "玄关",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 22,
      "Code": "men",
      "OriginalColumn": "PartId",
      "OriginalId": 21,
      "OriginalName": "门",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 23,
      "Code": "shuzhuo",
      "OriginalColumn": "PartId",
      "OriginalId": 20,
      "OriginalName": "书桌",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 24,
      "Code": "batai",
      "OriginalColumn": "PartId",
      "OriginalId": 19,
      "OriginalName": "吧台",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 25,
      "Code": "shujia",
      "OriginalColumn": "PartId",
      "OriginalId": 18,
      "OriginalName": "书架",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 26,
      "Code": "bogujia",
      "OriginalColumn": "PartId",
      "OriginalId": 17,
      "OriginalName": "博古架",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 27,
      "Code": "yigui",
      "OriginalColumn": "PartId",
      "OriginalId": 16,
      "OriginalName": "衣柜",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 28,
      "Code": "geduan",
      "OriginalColumn": "PartId",
      "OriginalId": 15,
      "OriginalName": "隔断",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 29,
      "Code": "zoulang",
      "OriginalColumn": "PartId",
      "OriginalId": 14,
      "OriginalName": "走廊",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 31,
      "Code": "piaochuang",
      "OriginalColumn": "PartId",
      "OriginalId": 12,
      "OriginalName": "飘窗",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 32,
      "Code": "louti",
      "OriginalColumn": "PartId",
      "OriginalId": 11,
      "OriginalName": "楼梯",
      "GroupId": 3,
      "GroupName": "局部",
      "ParaIn": [],
      "XgtUrl": "louti/",
      "CssText": ""
    },
    {
      "Id": 33,
      "Code": "mi",
      "OriginalColumn": "PartId",
      "OriginalId": 10,
      "OriginalName": "榻榻米",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 34,
      "Code": "jiugui",
      "OriginalColumn": "PartId",
      "OriginalId": 9,
      "OriginalName": "酒柜",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 35,
      "Code": "chuanglian",
      "OriginalColumn": "PartId",
      "OriginalId": 8,
      "OriginalName": "窗帘",
      "GroupId": 3,
      "GroupName": "局部",
      "ParaIn": [],
      "XgtUrl": "chuanglian/",
      "CssText": ""
    },
    {
      "Id": 36,
      "Code": "xiegui",
      "OriginalColumn": "PartId",
      "OriginalId": 7,
      "OriginalName": "鞋柜",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 37,
      "Code": "chugui",
      "OriginalColumn": "PartId",
      "OriginalId": 6,
      "OriginalName": "橱柜",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 38,
      "Code": "diaoding",
      "OriginalColumn": "PartId",
      "OriginalId": 5,
      "OriginalName": "吊顶",
      "GroupId": 3,
      "GroupName": "局部",
      "ParaIn": [],
      "XgtUrl": "diaoding/",
      "CssText": ""
    },
    {
      "Id": 39,
      "Code": "chuangtoubeijingqiang",
      "OriginalColumn": "PartId",
      "OriginalId": 4,
      "OriginalName": "床头背景墙",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 40,
      "Code": "shafabeijingqiang",
      "OriginalColumn": "PartId",
      "OriginalId": 3,
      "OriginalName": "沙发背景墙",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 41,
      "Code": "dianshibeijingqiang",
      "OriginalColumn": "PartId",
      "OriginalId": 2,
      "OriginalName": "电视背景墙",
      "GroupId": 3,
      "GroupName": "局部",
      "ParaIn": [],
      "XgtUrl": "dianshibeijingqiang/",
      "CssText": ""
    },
    {
      "Id": 42,
      "Code": "beijingqiang",
      "OriginalColumn": "PartId",
      "OriginalId": 1,
      "OriginalName": "背景墙",
      "GroupId": 3,
      "GroupName": "局部",
    },
    {
      "Id": 76,
      "Code": "gelou",
      "OriginalColumn": "PartId",
      "OriginalId": 26,
      "OriginalName": "阁楼",
      "GroupId": 3,
      "GroupName": "局部",
    }
  ],
  color: [
    {
      "Id": 1,
      "Code": "quanbu",
      "OriginalColumn": "ColorId",
      "OriginalId": 8,
      "OriginalName": "全部",
      "GroupId": 5,
      "GroupName": "感觉",
    },
    {
      "Id": 54,
      "Code": "hailan",
      "OriginalColumn": "ColorId",
      "OriginalId": 8,
      "OriginalName": "海蓝",
      "GroupId": 5,
      "GroupName": "感觉",
    },
    {
      "Id": 55,
      "Code": "huopo",
      "OriginalColumn": "ColorId",
      "OriginalId": 7,
      "OriginalName": "活泼",
      "GroupId": 5,
      "GroupName": "感觉",
    },
    {
      "Id": 57,
      "Code": "jiqing",
      "OriginalColumn": "ColorId",
      "OriginalId": 5,
      "OriginalName": "激情",
      "GroupId": 5,
      "GroupName": "感觉",
      "ParaIn": [],
      "XgtUrl": "jiqing/",
      "CssText": ""
    },
    {
      "Id": 58,
      "Code": "wennuan",
      "OriginalColumn": "ColorId",
      "OriginalId": 4,
      "OriginalName": "温暖",
      "GroupId": 5,
      "GroupName": "感觉",
    },
    {
      "Id": 59,
      "Code": "mingkuai",
      "OriginalColumn": "ColorId",
      "OriginalId": 3,
      "OriginalName": "明快",
      "GroupId": 5,
      "GroupName": "感觉",
    },
    {
      "Id": 60,
      "Code": "jianjie",
      "OriginalColumn": "ColorId",
      "OriginalId": 2,
      "OriginalName": "简洁",
      "GroupId": 5,
      "GroupName": "感觉",
    },
    {
      "Id": 61,
      "Code": "qingxin",
      "OriginalColumn": "ColorId",
      "OriginalId": 1,
      "OriginalName": "清新",
      "GroupId": 5,
      "GroupName": "感觉",
    }
  ],
  type: [
      {
          "Id": 1,
          "Code": "quanbu",
          "OriginalColumn": "TypeId",
          "OriginalId": 1,
          "OriginalName": "全部",
          "GroupId": 4,
          "GroupName": "户型",
          "ParaIn": [],
          "XgtUrl": "quanbu/",
          "CssText": ""
      },
      {
          "Id": 43,
          "Code": "xiaohuxing",
          "OriginalColumn": "TypeId",
          "OriginalId": 1,
          "OriginalName": "小户型",
          "GroupId": 4,
          "GroupName": "户型",
          "ParaIn": [],
          "XgtUrl": "xiaohuxing/",
          "CssText": ""
      },
      {
          "Id": 44,
          "Code": "sanju",
          "OriginalColumn": "TypeId",
          "OriginalId": 2,
          "OriginalName": "三居",
          "GroupId": 4,
          "GroupName": "户型",
          "ParaIn": [],
          "XgtUrl": "sanju/",
          "CssText": ""
      },
      {
          "Id": 45,
          "Code": "siju",
          "OriginalColumn": "TypeId",
          "OriginalId": 3,
          "OriginalName": "四居",
          "GroupId": 4,
          "GroupName": "户型",
          "ParaIn": [],
          "XgtUrl": "siju/",
          "CssText": ""
      },
      {
          "Id": 46,
          "Code": "yueju",
          "OriginalColumn": "TypeId",
          "OriginalId": 4,
          "OriginalName": "跃层",
          "GroupId": 4,
          "GroupName": "户型",
          "ParaIn": [],
          "XgtUrl": "yueju/",
          "CssText": ""
      },
      {
          "Id": 48,
          "Code": "bieshu",
          "OriginalColumn": "TypeId",
          "OriginalId": 5,
          "OriginalName": "别墅",
          "GroupId": 4,
          "GroupName": "户型",
          "ParaIn": [],
          "XgtUrl": "bieshu/",
          "CssText": ""
      },
      {
          "Id": 74,
          "Code": "gongyu",
          "OriginalColumn": "TypeId",
          "OriginalId": 6,
          "OriginalName": "公寓",
          "GroupId": 4,
          "GroupName": "户型",
          "ParaIn": [],
          "XgtUrl": "gongyu/",
          "CssText": ""
      },
      {
          "Id": 75,
          "Code": "erju",
          "OriginalColumn": "TypeId",
          "OriginalId": 7,
          "OriginalName": "二居室",
          "GroupId": 4,
          "GroupName": "户型",
          "ParaIn": [],
          "XgtUrl": "erju/",
          "CssText": ""
      }
  ],
  m: [
    {
        "Id": 1,
        "Code": "qiamni",
        "OriginalColumn": "Mid",
        "OriginalId": 1,
        "OriginalName": "全部",
        "GroupId": 4,
        "GroupName": "户型",
        "ParaIn": [
            0,
            60
        ],
        "XgtUrl": "0m/",
        "CssText": ""
    },
    {
        "Id": 49,
        "Code": "0m",
        "OriginalColumn": "Mid",
        "OriginalId": 1,
        "OriginalName": "60平米以下",
        "GroupId": 4,
        "GroupName": "户型",
        "ParaIn": [
            0,
            60
        ],
        "XgtUrl": "0m/",
        "CssText": ""
    },
    {
        "Id": 50,
        "Code": "60m",
        "OriginalColumn": "Mid",
        "OriginalId": 2,
        "OriginalName": "60-80平米",
        "GroupId": 4,
        "GroupName": "户型",
        "ParaIn": [
            60,
            80
        ],
        "XgtUrl": "60m/",
        "CssText": ""
    },
    {
        "Id": 51,
        "Code": "80m",
        "OriginalColumn": "Mid",
        "OriginalId": 3,
        "OriginalName": "80-100平米",
        "GroupId": 4,
        "GroupName": "户型",
        "ParaIn": [
            80,
            100
        ],
        "XgtUrl": "80m/",
        "CssText": ""
    },
    {
        "Id": 52,
        "Code": "100m",
        "OriginalColumn": "Mid",
        "OriginalId": 4,
        "OriginalName": "100-120平米",
        "GroupId": 4,
        "GroupName": "户型",
        "ParaIn": [
            100,
            120
        ],
        "XgtUrl": "100m/",
        "CssText": ""
    },
    {
        "Id": 53,
        "Code": "120m",
        "OriginalColumn": "Mid",
        "OriginalId": 5,
        "OriginalName": "120平米以上",
        "GroupId": 4,
        "GroupName": "户型",
        "ParaIn": [
            120,
            500000
        ],
        "XgtUrl": "120m/",
        "CssText": ""
    }
  ]
});